### ISSUE TITLE
gnome 45?

### ISSUE THREAD

**Issue by gaussandhisgun** [MrShuster/maximize_lonely_window#1]
gnome 45 changed the way imports work, and your extension is one of the 8 that keep me on out of date software. i think a lot of people that share your point of view, me included, would appreciate a gnome 45 port of this. thanks!

**Comment by MrShuster** [comment]
I have updated the extension to support gnome 45, the extension is in review on gnome extensions :)

**Comment by gaussandhisgun** [comment]
seems to not work with gnome 45 on my endeavourOS vm that i test extensions on while waiting for all of them to update so i can update my main to gnome 45. no errors, no logs, but the windows are not maximized either
