### ISSUE TITLE
Does not work with Gnome 45 (even after the added support)

### ISSUE THREAD

**Issue by gaussandhisgun** [MrShuster/maximize_lonely_window#2]
seems to not work with gnome 45 on my endeavourOS vm that i test extensions on while waiting for all of them to update so i can update my main to gnome 45. no errors, no logs, but the windows are not maximized either

_Originally posted in https://github.com/MrShuster/maximize_lonely_window/issues/1#issuecomment-1773888817_

**Comment by gaussandhisgun** [comment]
even weirder than that, it seems to work *fine* after i updated my host to gnome 45.

**Comment by MrShuster** [comment]
not sure why the extension did not work for you in a vm running endeavourOS, the problem might be unrelated to the extension.

**Comment by MrShuster** [comment]
I have updated the extension to support multiple monitors, this might fix the issue you were witnessing
